### ISSUE TITLE
[BUG] 'latest' is pointing to pre-releases

### ISSUE THREAD

**Issue by LongLiveCHIEF** [OctoPrint/octoprint-docker#102]
The `latest` tag is only meant to point to full releases, but currently the workflows are considering pre-releases as `latest`.

**Comment by LongLiveCHIEF** [comment]
It looks like this ran when I was testing changes to workflows, and was not triggered via dispatch.

**Comment by jwaes** [comment]
Having the same issue ... 'watchtower' upgraded my image to :latest, then i got a message inside octoprint to 'upgrade' ... which was a downgrade to 1.4.2 and that fscked up my install.

**Comment by LongLiveCHIEF** [comment]
>So the issue is that the jquery files are no longer there in the 'downgrade', as they moved to 1 js file ?

@jwaes this is most likely not a problem exclusive to docker, but I'll take a look.
