### ISSUE TITLE
Add migration notes for using the 3.0.0 image

### ISSUE THREAD

**Issue by morganchristiansson** [OctoPrint/octoprint-docker#138]
**Describe the bug**
After `docker-compose pull && docker-compose up -d` all my data was gone. Looking inside the container it's created new folder structure under `/octoprint/octoprint` whereas previously they were in `/octoprint`

Seems to affect 1.5.0, 1.5.1 and 1.5.2 docker images which all have been pushed in the last 2 days.

**To Reproduce**
```
docker-compose exec octoprint1 bash -l
ls -l /octoprint/octoprint
```

**Expected behavior**
Files used to live directly under /octoprint

**Workaround**
I first moved everything to /octoprint/octoprint but plugins stopped working. I guess they should still be in /octoprint/plugins ?

To make things simple I just created symlink using `ln -s . octoprint` inside /octoprint (outside or inside docker) and everything is back again.

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Browser n/a
 - Version 1.5.2 / 1.5.x

**Comment by cp2004** [comment]
I think this is detailed in the release notes [V3.0.0](https://github.com/OctoPrint/octoprint-docker/releases/tag/3.0.0)

I'll leave someone else to figure out if it is an actual bug, but just wanted to make sure you had read them to see if this explains the behaviour.

**Comment by LongLiveCHIEF** [comment]
Yeah, I was afraid of this, which is why the latest release was a breaking change. I readily admit I should have done a better job of identifying the impact and mitigation steps.  I'll get started on that now.

**Comment by LongLiveCHIEF** [comment]
Just FYI moving everything from `/octoprint/octoprint` was the right instinct, and there was just a missing second step, which was moving the `/octoprint/octoprint/plugins/python3.8` directory to `/octoprint/plugins`.  that directory contains the actual plugin binaries

**Comment by LongLiveCHIEF** [comment]
> An upgrade note / breaking changes note in README would've been nice

There are breaking change notes in both the CHANGELOG and in releases.  Even if I put the notes in README, you wouldn't see them before you updated. Whereas with the breaking changes being in the changelog and in releases, gitlab has built-in notification functionality for you by clicking Watch > custom > releases.

In addition to that, I have pinned in both docker channels in discord when there are breaking changes.

Users need to take some responsibility to check for changes before pulling new images, and I'm doing everything I can to push notifications in multiple places and ways.

**Comment by LongLiveCHIEF** [comment]
@morganchristiansson I've made a change to the README in PR #142 that contains the following language. Can you read it over and let me know if you think that would have worked for you had it been there beforehand?

> The `octoprint/octoprint` image uses semantic versioning, but the tags for `octoprint/octoprint` follow the
version of octoprint contained in the image. As a result we recommend you always check the [CHANGELOG](CHANGELOG.md)
or [Releases](https://github.com/OctoPrint/octoprint-docker/releases) before pulling an image, _even if you are pulling the same tag_.

>You can subscribe to be notified of releases as well, by selecting the Watch button in the upper right corner, 
choosing "Custom", and checking "Releases".

>In addition, we know that OctoPrint is not the best suited type of application for containerization, but we're
working hard to make it as compatible as possible. Please check out our [Roadmap](https://github.com/OctoPrint/octoprint-docker/projects/4),
or join the discussion in the `#dev-docker` or `#support-docker` channels on the official OctoPrint Discord
[discord.octoprint.org](https://discord.octoprint.org).
