### ISSUE TITLE
octoprint-docker supported on IOTstack

### ISSUE THREAD

**Issue by Paraphraser** [OctoPrint/octoprint-docker#188]
Not really an issue but…

<hr>

In case anyone is interested, this excellent [OctoPrint/octoprint-docker](https://github.com/OctoPrint/octoprint-docker) container is now supported at [IOTstack](https://github.com/SensorsIot/IOTstack):

* [service definition](https://github.com/SensorsIot/IOTstack/blob/master/.templates/octoprint/service.yml)

	* gets inserted into `docker-compose.yml` along with the service definitions for any other containers you might want to run.

* [documentation](https://sensorsiot.github.io/IOTstack/Containers/Octoprint/) which includes:

	* [how to update the container](https://sensorsiot.github.io/IOTstack/Containers/Octoprint/#routine-container-maintenance) - see also [Issue 183](https://github.com/OctoPrint/octoprint-docker/issues/183).

I've also written a [gist](https://gist.github.com/Paraphraser/650eeab26794dc7363b7123b33f671c4#file-docker-octoprint-when-your-3d-printer-turns-on-and-off-md) on how to get your RPi to sense when your 3D printer turns on and off, and react accordingly, so that your OctoPrint service is pretty much "always on", even if you like to keep your printer switched off unless you actually need it.

**Comment by LongLiveCHIEF** [comment]
Thanks for letting me know! I went back and reviewed the PR where they added support and left some comments on a few recommended changes to their docs.
