### ISSUE TITLE
Create docker image of current octoprint and replicate

### ISSUE THREAD

**Issue by treehuggersystems** [OctoPrint/octoprint-docker#200]
So, I have been successful in creating a docker version of octoprint and it seems to be working with no issues (at the moment) but my desire is to be able to get this one container exactly how I like it and then duplicate it. That being said I've tried a couple "how-to's" on how this can be done with standard docker containers but have had zero luck in getting it to function via octoprint. When I replicate my issue is, is that it will create the container just fine and install octoprint but it doesn't have any of the settings that I created in the previous container. SOOOO, what's the point, right?  If someone could try this and see if they're having similar issues or perhaps describe why this seems to be an issue for me I would greatly appreciate it.

**Comment by LongLiveCHIEF** [comment]
You might want to check out the [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/) command, as it was designed for this exact purpose.  The other thing to do would be to run a backup from the OctoPrint UI in your existing container, then start a new fresh container and import that backup, which should load all the plugins and restore your settings.
