### ISSUE TITLE
Docu / Container update for WebRTC usage

### ISSUE THREAD

**Issue by isarrider** [OctoPrint/octoprint-docker#222]
Hallo team,

just as an inquiry,
is there a plan to update the documentation
on how to run without MJPEG streamer and instead
via WebRTC?
Additionally, the containers will get an update then too?

(Is btw the WebRTC stream HW encoding accelerated)?

BR,
Alex

**Comment by LongLiveCHIEF** [comment]
WebRTC would require a very complex setup specific to an individual users network. Hardware acceleration is again something docker is not really built for.
