### ISSUE TITLE
Q: How do I get the webcam working usign ngrok?

### ISSUE THREAD

**Issue by jorgegomzar** [OctoPrint/octoprint-docker#224]
## Question/Problem Description

I moved from Octopi to this octoprint container. Everything works fine except for the fact that I cannot get the webcam to work through a ngrok tunnel (using the octoprint plugin).
May it be related to a firewall inside the octoprint image? Or may it be related to the docker config of the network used?

### System Details

I'm running octoprint docker using the `docker-compose.yml` file:
![image](https://user-images.githubusercontent.com/34076979/167293455-b107b06b-ba55-41e4-8f51-cdc1902e1e34.png)

![image](https://user-images.githubusercontent.com/34076979/167293305-9c1a7218-332e-49f4-9085-fc48d33d5c8a.png)

**Comment by franz134** [comment]
I have exactly the same issue.
First I read out the devices as shown and strangely got 2 video devices, despite only one webcam is plugged in. (also tried a usb-capturecard - also 2 video devices recognized, same issue)
![Screenshot 2022-05-12 103116](https://user-images.githubusercontent.com/98423516/168030665-2e312958-5666-4b21-bc34-e92c657aa064.png)
In the .yaml file I use "video0" but I also tried video1 - no difference.
![Screenshot 2022-05-12 103347](https://user-images.githubusercontent.com/98423516/168031126-b794ffa9-1887-4816-956f-fedaf8da2750.png)
So I got octoprint up and running, but no webstream in the control tab.
![Screenshot 2022-05-12 103606](https://user-images.githubusercontent.com/98423516/168032622-551552f8-0615-4549-b74a-308fa543eff7.png)
However I have made an interesting discovery: the feature of making timelapse is working and in the settings I can test the snapshots, but I have no clue why the stream isn't working.
![Screenshot 2022-05-12 105720](https://user-images.githubusercontent.com/98423516/168033894-441e98b3-8dcd-4201-a5eb-36520f713333.png)

**Comment by franz134** [comment]
I've found the solution, at least for my problem, after quite a while of research in the octoprint forum:
https://community.octoprint.org/t/octoprint-in-docker-snapshot-works-stream-doesnt/43699
I had to write `ports: - 5000:80` instead of my `5000:5000`
Not sure if this also fixes your issue, but maybe it's worth trying.
