### ISSUE TITLE
Q: what is the preffered method of updating the octoprint-docker container?

### ISSUE THREAD

**Issue by pathia** [OctoPrint/octoprint-docker#241]
The Octoprint web gui is giving me update notifications and I can just update my container but in the end if I recreate the container I have an older version octoprint using the storage in my volume which is previously used by a later version.
So my question is: What is the preffered method of updating the octoprint-docker container?
Update it using a container upgrade only (using watchtower or something like that) or just use the update buttons on the Octoprint web gui and just keep it simple..?

**Comment by LongLiveCHIEF** [comment]
I recommend updating using the upgrade buttons within octoprint UI.
