### ISSUE TITLE
Multiple processes of mjpg streamer started

### ISSUE THREAD

**Issue by eRaz3r** [OctoPrint/octoprint-docker#249]
Don't know since when but when I start my container of octoprint there are multiple processes for the mjpeg streamer. I absolutely don't know what this about but it seems not normal.

![process](https://user-images.githubusercontent.com/8236933/221886360-29b897fa-c826-4efa-9c2e-991ae34ec4bb.png)
![protocoll](https://user-images.githubusercontent.com/8236933/221886400-05013b67-ebca-4cce-99ea-385f3b996986.png)

**Comment by LongLiveCHIEF** [comment]
When was the last time you pulled the octoprint container?  I'm wondering if this was a bug introduced in https://github.com/OctoPrint/octoprint-docker/pull/245

**Comment by eRaz3r** [comment]
> When was the last time you pulled the octoprint container? I'm wondering if this was a bug introduced in #245

There were two updates since I noticed this problem.

**Comment by LongLiveCHIEF** [comment]
When was the last time you pulled the octoprint container?

**Comment by LongLiveCHIEF** [comment]
I'm pretty sure this was introduce in #245, and that you are running an octoprint image that was pulled after that was pushed to docker hub.  I'm going to revert that change here shortly and publish the fix up to docker hub.

**Comment by eRaz3r** [comment]
I hope you're right. I am running an octoprint docker on another server without this problem. I will pull the container and will see. Thank you very much for your fast reply.

**Comment by eRaz3r** [comment]
> I'm pretty sure this was introduce in #245, and that you are running an octoprint image that was pulled after that was pushed to docker hub. I'm going to revert that change here shortly and publish the fix up to docker hub.

Problem seems to be fixed. Thank you very much. Any chance that a noob like me understands what the problem was about?

**Comment by jniclas** [comment]
Hey, thank you for fixing this so fast! 👍🏻 
After pulling the image again, everything worked great again.
Because I was googleing a lot until I found this, because the logs are posted only as image, I shortly post my logs as text, so others may find this issue faster:

```
Starting mjpg_streamer for camera device /dev/video0 on port 8080
enabling daemon modeforked to background (4474)
Starting mjpg_streamer for camera device /dev/video0 on port 8080
enabling daemon modeforked to background (4481)
Starting mjpg_streamer for camera device /dev/video0 on port 8080
enabling daemon modeforked to background (4488)
Starting mjpg_streamer for camera device /dev/video0 on port 8080
enabling daemon modeforked to background (4495)
Starting mjpg_streamer for camera device /dev/video0 on port 8080
enabling daemon modeforked to background (4502)
...
```
