### ISSUE TITLE
README updates for tag list

### ISSUE THREAD

**Issue by LongLiveCHIEF** [OctoPrint/octoprint-docker#29]
Update README to include a list of docker tags, similar to that you would find on all the official images on docker hub.

Each tag should link back to the respective Dockerfile (at the moment they're all built from the same one)

**Comment by LongLiveCHIEF** [comment]
Here's the tagging convention we've decided to go with:

```
latest, X.Y.Z, X.Y, X, latest-python3, X.Y.Z-python3, X.Y-python3 X-python3
latest-camera, X.Y.Z-camera, X.Y-camera, X-camera, X.Y.Z-python3-camera, X.Y-python3-camera, latest-python3-camera
latest-python2, x-python2, X.Y-python2, X.Y.Z-python2
latest-python2-camera, x-python2-camera, X.Y-python2-camera, X.Y.Z-python2-camera
```

See relevant discussion on discord: https://discordapp.com/channels/704958479194128507/712573137325391973/736600275397247016

**Comment by Mearman** [comment]
Are the `X.Y` versions going to be the latest patch version for that minor version?

**Comment by LongLiveCHIEF** [comment]
@Mearman that's correct.  It'll follow the conventions of most official images. When a new patch is released, each row listed above will all point to the same image digest.
