### ISSUE TITLE
no "/webcam" address support in camera versions

### ISSUE THREAD

**Issue by rcdemuth** [OctoPrint/octoprint-docker#65]
This is more of a PSA than a bug report, I wanted to let other people know how to make a webcam work.

From my experience with some other (non-official) docker images, as well as octopi, the standard octorprint address for a video stream, given a properly connected usb webcam is '/webcam/?action=stream'

This format currently does not work with this image. However, '<youripaddress>:8080/?action=stream' does work. 

I've looked at the files and settings related to the camera and mjpg-streamer.  I can't really find any reference that would replace /webcam/.

**Comment by LongLiveCHIEF** [comment]
The `/webcam` endpoint is configured via the `haproxy.cfg` https://github.com/OctoPrint/octoprint-docker/blob/master/camera/etc/haproxy/haproxy.cfg#L32. 

This is reachable at the container port `8888`.  You will need to map a given host port to `8888` with the camera image, and if you don't want to have to type in a port number in the url, you'll use the `80:8888` mapping.

This image _is_ replacing the nunofgs image, and this will be one change from how that image is used.

**Comment by LongLiveCHIEF** [comment]
closed with #69
